#!/usr/bin/env python3
"""
push_to_github.py  –  CLI to push any local folder to a new GitHub repo
=========================================================================

Usage:
    python push_to_github.py <local_path> [--name <repo-name>] [--owner <org>] [--private] [--branch <branch>]

Examples:
    python push_to_github.py  C:\temp\migrations\petclinic-microservices
    python push_to_github.py  C:\temp\migrations\petclinic-microservices  --name petclinic-ms  --private
    python push_to_github.py  ./output  --owner qlikaccel  --branch develop

The GITHUB_TOKEN is read from the .env file or environment variable.
"""

import argparse
import sys
import os

# Ensure we can import from the project
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from dotenv import load_dotenv
load_dotenv()

from services.github_autopush_service import github_autopush


def main():
    parser = argparse.ArgumentParser(
        description="Push a local directory to a new GitHub repository",
    )
    parser.add_argument("local_path", help="Path to the local folder to push")
    parser.add_argument("--name", dest="repo_name", default=None, help="Repository name (default: folder name + timestamp)")
    parser.add_argument("--owner", default=None, help="GitHub org or username (default: token owner)")
    parser.add_argument("--token", default=None, help="GitHub PAT (default: GITHUB_TOKEN from .env)")
    parser.add_argument("--private", action="store_true", help="Create a private repo")
    parser.add_argument("--branch", default="main", help="Branch name (default: main)")
    parser.add_argument("--message", default="Initial commit – auto-generated by JavaAPEX", help="Commit message")
    parser.add_argument("--enterprise-url", default=None, help="GitHub Enterprise base URL")

    args = parser.parse_args()

    print(f"📦 Pushing '{args.local_path}' to GitHub …")
    result = github_autopush.push(
        local_path=args.local_path,
        repo_name=args.repo_name,
        token=args.token,
        owner=args.owner,
        private=args.private,
        branch=args.branch,
        commit_message=args.message,
        enterprise_url=args.enterprise_url,
    )

    if result.success:
        print(f"✅ Success!")
        print(f"   Repo : {result.repo_url}")
        print(f"   Branch: {result.branch}")
        print(f"   Files : {result.files_pushed}")
    else:
        print(f"❌ Failed: {result.error}")
        sys.exit(1)


if __name__ == "__main__":
    main()
